global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'pushgateway'
    honor_labels: true # Do not overwrite labels from pushed metrics
    static_configs:
      - targets: ['pushgateway:9091']
