version: "2"
sql:
  - engine: "postgresql"
    schema: "../../../contracts/pgsql/migrations"
    queries: "../../../internal/adapter/repository/postgresql/sql"
    gen:
      go:
        package: "sqlc"
        out: "../../../internal/adapter/repository/postgresql/sqlc"
        sql_package: "pgx/v5"
        emit_json_tags: true
        emit_interface: true
        overrides:
          - db_type: "uuid"
            go_type: "github.com/google/uuid.UUID"
